/**
 * A tiny, dependency-free tokenizer for the three snippet languages.
 *
 * Why not Shiki / Prism / highlight.js: the only code this app ever highlights
 * is generated by `snippets.ts` — three short, fully-known templates. A real
 * highlighter would add 200 kB-plus (or a WASM grammar) to the critical path of
 * the page whose whole job is to be fast and indexable, in exchange for
 * colouring text we wrote ourselves. This is ~80 lines and runs at render time.
 *
 * It is deliberately NOT a general-purpose lexer. It is correct for the output
 * of `pythonSnippet`, `typescriptSnippet` and `curlSnippet`, and its failure
 * mode on anything else is "some words are not coloured" — never broken markup,
 * because the caller renders tokens as React children and never as HTML.
 */

export type TokenKind = "plain" | "comment" | "string" | "keyword" | "number" | "property";

export type Token = { kind: TokenKind; text: string };

export type Grammar = "python" | "typescript" | "bash";

type Rule = { kind: TokenKind; re: RegExp };

/**
 * Rules are tried in order at each position, so comments and strings must come
 * before anything that could match inside them.
 *
 * Every pattern is anchored with `y` (sticky) and used via `lastIndex`, which is
 * what makes an ordered single-pass scan possible without slicing the input.
 */
const RULES: Readonly<Record<Grammar, readonly Rule[]>> = {
  python: [
    { kind: "comment", re: /#[^\n]*/y },
    { kind: "string", re: /"""[\s\S]*?"""|'''[\s\S]*?'''|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/y },
    {
      kind: "keyword",
      re: /\b(?:from|import|as|def|class|return|for|in|if|elif|else|while|with|try|except|finally|and|or|not|is|None|True|False|lambda|yield|await|async|pass|raise|print)\b/y,
    },
    { kind: "number", re: /\b\d[\d_]*(?:\.\d+)?\b/y },
    { kind: "property", re: /\b[A-Za-z_]\w*(?=\s*\()/y },
  ],
  typescript: [
    { kind: "comment", re: /\/\/[^\n]*|\/\*[\s\S]*?\*\//y },
    { kind: "string", re: /`(?:\\.|[^`\\])*`|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/y },
    {
      kind: "keyword",
      re: /\b(?:import|from|export|default|const|let|var|function|return|await|async|new|for|of|in|if|else|while|try|catch|finally|class|extends|type|interface|as|true|false|null|undefined|void|typeof)\b/y,
    },
    { kind: "number", re: /\b\d[\d_]*(?:\.\d+)?\b/y },
    { kind: "property", re: /\b[A-Za-z_$][\w$]*(?=\s*\()/y },
  ],
  bash: [
    { kind: "comment", re: /#[^\n]*/y },
    // Single quotes in POSIX sh are literal and have no escapes — which is
    // exactly why the cURL snippet wraps its JSON body in them, and why this
    // pattern must not honour backslashes inside them.
    { kind: "string", re: /'[^']*'|"(?:\\.|[^"\\])*"/y },
    { kind: "keyword", re: /(?:^|(?<=\s))-{1,2}[A-Za-z][\w-]*/y },
    { kind: "property", re: /\$\{?\w+\}?/y },
    { kind: "number", re: /\b\d+\b/y },
  ],
};

/**
 * Split `code` into coloured tokens.
 *
 * Adjacent `plain` characters are merged so the DOM holds one text node per run
 * rather than one span per character.
 */
export function tokenize(code: string, grammar: Grammar): Token[] {
  const rules = RULES[grammar];
  const out: Token[] = [];
  let plain = "";
  let i = 0;

  const flush = () => {
    if (plain) {
      out.push({ kind: "plain", text: plain });
      plain = "";
    }
  };

  while (i < code.length) {
    let matched = false;

    for (const rule of rules) {
      rule.re.lastIndex = i;
      const m = rule.re.exec(code);
      if (m && m[0].length > 0) {
        flush();
        out.push({ kind: rule.kind, text: m[0] });
        i += m[0].length;
        matched = true;
        break;
      }
    }

    if (!matched) {
      plain += code[i];
      i += 1;
    }
  }

  flush();
  return out;
}

/**
 * Token → Tailwind class.
 *
 * These point at the dedicated `--code-*` tokens (DESIGN.md §1.4), NOT at the
 * semantic status colours. Syntax and status are different jobs: borrowing
 * `text-success` for a string literal worked only while the accent was violet
 * and success was green. With a green accent, `keyword` and `string` would be
 * near-neighbours and the highlighting would stop distinguishing anything.
 *
 * All five are contrast-checked against `--surface`, which is what a code block
 * sits on, in both themes. `--code-keyword` deliberately equals `--accent` so
 * the block reads as part of the product; everything else diverges.
 */
export function tokenClassName(kind: TokenKind): string {
  switch (kind) {
    case "comment":
      return "text-code-comment italic";
    case "string":
      return "text-code-string";
    case "keyword":
      return "text-code-keyword font-medium";
    case "number":
      return "text-code-number";
    case "property":
      return "text-code-property";
    case "plain":
      return "";
  }
}
